id: PAD105AAA
initial_creation_type: input
source_metadata:
  title: Dolpopa Sherab Gyaltsen
  language: bo
  description: Texts by and about Dolpopa Sherab Gyaltsen (dol po pa shes rab rgyal
    mtshan, 1292–1361), who was one of the most influential masters in Tibetan history.
    He trained in the Sakya tradition and then moved to Jonang Monastery, where he
    established a formidable yet controversial scholarly tradition.
  volume:
    fbab9da2023c483aafc40a37a7bd2002:
      title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
        the Great Omniscient Jonangpa from Afar'
      parent: Calling the Guru from Afar
    b3ee3d5e98a3479e90b6c0072a0e122d:
      title: Guru Sādhana of the Omniscient Dolpopa
      parent: Guru Yoga
    8d83107e41234cea9d5d8c67f97e318e:
      title: Aspiration Prayer of the Ultimate Definitive Meaning
      parent: Prayers
    ae5734e9dd704c0b8eb2f6764caa213e:
      title: In Praise of the Eight Siddhas
      parent: Prayers
created_at: '2022-02-28T23:02:01.164515'
last_modified_at: '2022-02-28T23:02:01.164518'
